#!/bin/bash -e

# (C) 2007 Daniel Kahn Gillmor <dkg-debian.org>
# This file is released under the GNU GPL v3 or later

# run this script from the top level of your working directory to
# build a debian package in ./build

# you must have the svn and devscripts packages installed.

##################################################

# find the program name from the svn directory
PGM=$(basename $(pwd))

# find the repository path:
REPO=$(svn info | grep ^URL:\ | awk '{ print $2 }')

# extract the version number from the changelog:
VERS=$(head -n1 debian/changelog | awk '{ print $2 }' | sed 's|[^[:digit:].]||g')

PKG="$PGM-$VERS"

# export the baseline from the repo into a clean directory:
rm -rf ./build/"$PKG"
mkdir -p ./build
svn export "$REPO" ./build/"$PKG"

# apply any unapplied changes from the wd to the building copy:
svn diff | (cd ./build/"$PKG" && patch -p0)

# actually build:
(cd ./build/"$PKG" && debuild -uc -us)
