#!/bin/bash

METHOD=0
#http_proxy=http://proxy.lair.fifthhorseman.net:3128/

cd /srv/debirf

# start by fetching initramfs-tools because they'll be handy
/usr/sbin/debootstrap --exclude=aptitude --include=initramfs-tools etch ./root/ http://ftp.debian.org/debian

echo debirf > root/etc/hostname
cat >root/etc/kernel-img.conf <<EOF
# debirf: default kernel-img options:
do_symlinks = yes
do_bootloader = no
do_initrd = yes
EOF

cat >>root/etc/inittab <<EOF
# debirf: added serial console output:
T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100
EOF

cat >>root/etc/network/interfaces <<EOF
# debirf: some needed interfaces:
auto lo
iface lo inet loopback

# a default dynamic ethernet address.
# if you have eth0, you can use this with "ifup eth0=dhcp"
iface dhcp inet dhcp
EOF


mount -t proc proc root/proc
mount -t sysfs sys root/sys

# set $KERNEL_PACKAGE to the path to a kernel .deb if you have one
# lying around:
if [ "$KERNEL_PACKAGE" ]; then
    KNAME=$(basename "$KERNEL_PACKAGE")
    cp "$KERNEL_PACKAGE" "root/root/$KNAME"
    chroot root dpkg --install "root/$KNAME"
else
    chroot root apt-get update
    chroot root apt-get install linux-image-2.6-486
fi

# clean apt?
if false ; then
    chroot root apt-get clean
    rm root/var/cache/apt/*.bin
    rm -rf root/var/lib/apt/lists/*
    mkdir root/var/lib/apt/lists/partial
fi

umount root/proc
umount root/sys

mkdir -p extras/boot

mv root/boot/vmlinuz-* extras/boot
mv root/boot/initrd.img-* extras/boot

# remove/backup locales:
mkdir -p extras/usr/share/locale
(cd root && find usr/share/locale -maxdepth 1 -mindepth 1 -type d ! -iname 'en*' -exec mv '{}' '../extras/{}' \; )


# stupid simple method
if [ "$METHOD" = 0 ] ; then
    > root/etc/mtab
    echo proc /proc proc defaults 0 0 >> root/etc/fstab
    ln -s sbin/init root/init
    (cd root && find * | cpio -H newc --create  | gzip ) > debirf.cgz
fi


# tweak initrd method
if [ "$METHOD" = 1 ] ; then


cat scripts/debirf <<EOF
mountroot() {
 rootmnt="/"
}
EOF

cat > bin/run-init <<EOF
#!/bin/sh
if [ "$1" != "/" ] ; then
  exec /usr/lib/klibc/bin/run-init "$@"
else
  MOUNT_POINT="$1"
  INIT="$2"
  shift 2
  exec "$INIT" "$@"
fi
EOF

fi
