#!/bin/bash -e

# debirf module: rescue
# remove/install extra packages for disk rescue with apt-get
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

# preseed.  helpful link:
# http://blog.hjksolutions.com/articles/category/solutions
debirf_exec debconf-set-selections <<EOF
# Do you want to start MD arrays automatically?
mdadm mdadm/autostart boolean false
# MD arrays needed for the root filesystem:
mdadm mdadm/initrdstart string none
# Proceed with starting arrays not listed in mdadm.conf?
mdadm mdadm/initrdstart_notinconf boolean false
# Do you want to start the MD monitoring daemon?
mdadm mdadm/start_daemon boolean false
# Recipient for email notifications:
mdadm mdadm/mail_to string root
# Should mdadm run monthly redundancy checks of the MD arrays?
mdadm mdadm/autocheck boolean false
EOF

# install packages
debirf_exec apt-get --no-install-recommends --assume-yes install \
 lvm2 \
 lsof \
 hdparm \
 parted \
 pciutils \
 testdisk \
 foremost \
 mdadm \
 smartmontools \
 eject \
 wodim \
 ddrescue \
 cryptsetup \
 sdparm \
 hfsprogs \
 hfsutils \
 hfsplus \
 e2undel \
 recover \
 e2tools \
 fatresize \
 dosfstools \
 tofrodos \
 mtd-utils \
 grub2 \
 scrub \
 wipe \


# partimage is not available in amd64 on ubuntu at the moment -- we
# should still be able to build a rescue image without it, if it comes
# to that.

debirf_exec apt-get --no-install-recommends --assume-yes install partimage || true

# let's try some different configurations of uboot-related tools, since the
# package names seem to be in flux right now:

debirf_exec apt-get --no-install-recommends --assume-yes install u-boot-tools || \
    debirf_exec apt-get --no-install-recommends --assume-yes install uboot-envtools uboot-mkimage || \
    true
