#!/bin/bash

# debirf module: prep-root
# prep the debirf root with various needed files and info
#
# *** REQUIRED MODULE ***
# WARNING: this module is necessary for proper functioning of debirf.
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

# output info to the debirf.info file on the initramfs
mkdir -p "${DEBIRF_ROOT}/etc/debirf"
cat > "${DEBIRF_ROOT}/etc/debirf/debirf.info" <<EOF
# debirf.info
#
# $DEBIRF_LABEL
#
# debirf version: $(dpkg-query --show debirf | awk '{ print $2 }')
#     build host: $(hostname -f)
#     build arch: $(dpkg --print-architecture)
#     build date: $(date -R)

# the following config variables were set during build:
EOF
for var in ${!DEBIRF_*}; do
    debirf_info_sh "${var}=${!var}"
done

# initialize /etc/fstab
echo proc /proc proc defaults 0 0 > "${DEBIRF_ROOT}/etc/fstab"

# write /etc/hostname
echo "$DEBIRF_LABEL" > "${DEBIRF_ROOT}/etc/hostname"

# write /etc/hosts
cat > "${DEBIRF_ROOT}/etc/hosts" <<EOF
127.0.0.1	localhost
127.0.1.1       $DEBIRF_LABEL

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

# update apt
debirf_exec apt-get update
