#!/bin/sh

# debirf module: apt-get
# remove/install extra packages with apt-get
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

# why does aptitude not seem to be recognizing --without-recommends option?
# currently requires explicitly not installing:
# courier-mta mailx bsd-mailx
debirf_exec aptitude --without-recommends --assume-yes install less moreutils lvm2 lsof screen hdparm pciutils mdadm smartmontools courier-mta- mailx- bsd-mailx-

debirf_exec /etc/init.d/mdadm stop
