#!/bin/sh

# debirf module: root-passwd
# set password for root
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

echo "Set password for $DEBIRF_LABEL superuser:"
debirf_exec passwd
