#!/bin/bash -e

# debirf plugin: motd
# custom /etc/motd.tail file
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

cat > "${DEBIRF_ROOT}/etc/motd.tail" <<EOF

Welcome to debirf: DEBian on InitRamFs

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

EOF
