#!/bin/bash

# debirf plugin: prep-root
# prep the debirf root with various needed files and info
#
# WARNING: this plugin is necessary for proper functioning of other plugins.
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

# write all the debirf environment variables to the on-root debirf config file
debirf_info_comment 'the following config variables were set during build:'
for var in ${!DEBIRF_*}; do
    debirf_info_sh "${var}=${!var}"
done

# write /etc/hostname
echo "$DEBIRF_LABEL" > "${DEBIRF_ROOT}/etc/hostname"

# update apt
debirf_exec apt-get update
