#!/bin/sh

# debirf plugin: apt-get
# remove/install extra packages with apt-get
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

debirf_exec apt-get --assume-yes remove --purge aptitude

debirf_exec apt-get --assume-yes install less moreutils lvm2 mdadm lsof screen hdparm smartmontools

debirf_exec /etc/init.d/mdadm stop
