#!/bin/bash

# debirf plugin: install-kernel
# install a kernel package, indicated by the expected environment
# variables:
#  DEBIRF_PATH
#  DEBIRF_ROOT
#  DEBIRF_KERNEL_PACKAGE
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

if [ -f "$DEBIRF_KERNEL_PACKAGE" ] ; then
    KNAME=$(basename "$DEBIRF_KERNEL_PACKAGE")
    cp "$DEBIRF_KERNEL_PACKAGE" "$DEBIRF_ROOT/$KNAME"
else
    debirf_exec aptitude download "$DEBIRF_KERNEL_PACKAGE"
    KNAME=$(basename "$DEBIRF_ROOT"/linux-image-*)
fi

echo "extracting kernel package $KNAME..."
debirf_exec dpkg --extract "$KNAME" /

rm "$DEBIRF_ROOT/$KNAME"

# extract kernel and debian stock initrd:
mv "$DEBIRF_ROOT"/boot/vmlinu* "$DEBIRF_BUILDD"

# remove kernel symlinks
if [ -L "$DEBIRF_ROOT"/vmlinuz ] ; then
    rm "$DEBIRF_BUILDD"/vmlinuz
fi
