#!/bin/bash

# debirf plugin: install-kernel
# install a kernel package, indicated by the expected environment
# variables:
#  DEBIRF_PATH
#  DEBIRF_ROOT
#  DEBIRF_KERNEL_PACKAGE
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

install_kernel_dpkg() {
    local KNAME=$(basename "$1")
    cp "$1" "$DEBIRF_ROOT/root/$KNAME"
    debirf_exec dpkg --install "root/$KNAME"
    # and clean up, just in case there were missing dependencies.
    debirf_exec apt-get --assume-yes --force-yes -f install
    rm "$DEBIRF_ROOT/root/$KNAME"
}

install_kernel_apt() {
    debirf_exec apt-get --assume-yes install "$1"
}

install_kernel() {
    # kernel install settings
    cat >"$DEBIRF_ROOT/etc/kernel-img.conf" <<EOF
# debirf: default kernel-img options:
do_symlinks = no
do_bootloader = no
warn_initrd = no
silent_modules = yes
EOF

    if [ -f "$1" ] ; then
	install_kernel_dpkg "$1"
    else
	install_kernel_apt "$1"
    fi
    
    # extract kernel and debian stock initrd:
    mv "$DEBIRF_ROOT"/boot/vmlinu* "$DEBIRF_BUILDD"
    mv "$DEBIRF_ROOT"/boot/initrd* "$DEBIRF_BUILDD"

    # remove kernel symlinks
    [ -L "$DEBIRF_ROOT"/vmlinuz ] && rm "$DEBIRF_BUILDD"/vmlinuz
    [ -L "$DEBIRF_ROOT"/initrd.img ] && rm "$DEBIRF_BUILDD"/initrd.img

}

##### install kernel
install_kernel "$DEBIRF_KERNEL_PACKAGE"
