#!/bin/sh

# add default network interface configuration

cat > "$DEBIRF_ROOT"/etc/network/interfaces <<EOF
# Used by ifup(8) and ifdown(8). See the interfaces(5) manpage or
# /usr/share/doc/ifupdown/examples for more information.

auto lo
iface lo inet loopback

# a default dynamic ethernet address.
# if you have eth0, you can use this with "ifup eth0=dhcp"
iface dhcp inet dhcp
EOF

# reset default udev persistent-net rule

rm -f "$DEBIRF_ROOT"/etc/udev/rules.d/*_persistent-net.rules
