#!/bin/sh

# debirf plugin: interfaces
# add default network interface configuration
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

cat > "${DEBIRF_ROOT}/etc/network/interfaces" <<EOF
# Used by ifup(8) and ifdown(8). See the interfaces(5) manpage or
# /usr/share/doc/ifupdown/examples for more information.

auto lo
iface lo inet loopback

# a default dynamic ethernet address.
# if you have eth0, you can use this with "ifup eth0=dhcp"
iface dhcp inet dhcp
EOF

# reset default udev persistent-net rule
rm -f "$DEBIRF_ROOT"/etc/udev/rules.d/*_persistent-net.rules

# add comment to /etc/motd.tail
cat >> "${DEBIRF_ROOT}/etc/motd.tail" <<EOF

If you have a network interface (ie. "eth0"), you can bring it up with:
"ifup eth0=dhcp"
("ifconfig -a" will list available network interfaces.)
EOF
