#!/bin/bash

# debirf plugin: root-unionfs
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

debirf_exec apt-get install unionfs-modules-2.6.18-4-486 unionfs-tools

# cat >"$DEBIRF_ROOT/etc/init.d/root-unionfs" <<EOF
# #!/bin/bash

# mount -t tmpfs tmpfs /tmp
# mount -t unionfs dirs=/=ro:/tmp=rw unionfs /
# EOF

# ln -sf ../init.d/root-unionfs /etc/rcS.d/S00root-unionfs
