#!/bin/sh

# debirf plugin: serial-terminal
# add serial terminal
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

INITTAB="$DEBIRF_ROOT/etc/inittab"
TTY="ttyS0"

if grep "$TTY" "$INITTAB" | grep -q -v "^[:space:]*#" ; then
    echo "inittab already has terminal on $TTY."
else
    cat >> "$INITTAB" <<EOF
# debirf: added serial console output:
T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100
EOF
fi
