#!/bin/bash -e

# debirf plugin: store-config
# store the debirf build configuration information inside the initramfs
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

debirf_info_comment 'the following config variables were set:'

for var in ${!DEBIRF_*}; do
    debirf_info_sh "${var}=${!var}"
done
