#!/bin/bash -e

# debirf plugin: motd
# custom /etc/motd.tail file
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg-debian.org@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL, version 2
# or later.

cat >> "${DEBIRF_ROOT}/etc/motd.tail" <<EOF
--------------------------------------------------
EOF
