.TH BUILD-DEBIRF-KERNEL "1" "March 2007" "build-debirf-kernel 0.1" "User Commands"
.SH NAME
build-debirf-kernel \- build a kernel to boot a debian system entirely from RAM
.SH SYNOPSIS
.B build-debirf-kernel
.SH DESCRIPTION
.PP
Run \fBbuild-debirf-kernel\fP as a non-privileged user on a
properly-configured debian system to build a .deb kernel package that
can boot entirely from an initramfs.  Having such a deb is a
prerequisite for getting a debirf system up and running.
.PP
The debirf system is outlined at:
.PP
   http://cmrg.fifthhorseman.net/wiki/debirf
.PP
\fBbuild-debirf-kernel\fP will first check to ensure that you have the
proper packages installed on your system before proceeding.  It will
attempt to build a kernel that matches the kernel you are currently
running, with the addition of Kent Robotti's EARLYUSERSPACE_ON_TMPFS
(inittmpfs) patch.
.PD
.SH AUTHOR
Written by Jameson Rollins and Daniel Kahn Gillmor.
.SH "REPORTING BUGS"
Report bugs to <debirf@fifthhorseman.net>.
.SH COPYRIGHT
Copyright \(co 2007 Jameson Rollins and Daniel Kahn Gillmor
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR make-debirf (8),
.BR make-kpkg (1)
