#!/bin/sh

# debirf plugin to install a kernel package, indicated by the
# environment variable $DEBIRF_KERNEL_PACKAGE

install_kernel_dpkg() {
    local KNAME=$(basename "$1")
    cp "$1" "$DEBIRF_ROOT/root/$KNAME"
    chroot "$DEBIRF_ROOT" dpkg --install "root/$KNAME"
    # and clean up, just in case there were missing dependencies.
    chroot "$DEBIRF_ROOT" apt-get -f install
    rm "$DEBIRF_ROOT/root/$KNAME"
}

install_kernel() {
    # kernel install settings
    cat >"$DEBIRF_ROOT/etc/kernel-img.conf" <<EOF
# debirf: default kernel-img options:
do_symlinks = yes
do_bootloader = no
do_initrd = yes
EOF
    
    install_kernel_dpkg "$1"
    
    # extract kernel, debian stock initrd, and remove them from the fs:
    mv "$DEBIRF_ROOT"/boot/vmlinu* .
    mv "$DEBIRF_ROOT"/boot/initrd* .
}

##### install kernel
msg "installing kernel..."
install_kernel "$DEBIRF_KERNEL_PACKAGE"
